name: geolocator_w_firebase
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cloud_firestore: ^3.5.1
  firebase_core: ^1.24.0
  flutter:
    sdk: flutter
  geoflutterfire: ^3.0.2
  google_maps_flutter: ^2.5.3
  location: ^5.0.3
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
